version: "3.8"

services:
  mongodb_project2:
    image: mongo
    container_name: mongodb_project2
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - project2:/data/db

  project2_backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: project2_backend
    hostname: project2_backend
    restart: always
    ports:
      - "4001:4000"
    env_file:
      - ./backend/src/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  project2_client:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: project2_client
    hostname: project2_client
    ports:
      - "3001:3000"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - project2_backend
volumes:
  project2:

networks:
  default:
    name: nginx_reverse_proxy_gateway
    external: true
