version: "3.8"

services:
  mongodb_project2:
    image: mongo
    container_name: mongodb_project2
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - project2:/data/db

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "4001:4000"
    env_file:
      - ./backend/src/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: client
    ports:
      - "3001:5173"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
volumes:
  project2:
